# Generated by Django 3.0.5 on 2020-04-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='date joinde')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='', max_length=256)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other'), ('p', 'Prefer not to say')], default='p', max_length=1)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('avatar', models.FileField(blank=True, null=True, upload_to='users_media/<django.db.models.fields.CharField>/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
