# Generated by Django 3.0.5 on 2020-04-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FilePathField(blank=True, default=None, null=True),
        ),
    ]
